name: ayur_scoliosis_management
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  dio: ^5.8.0+1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
